#!/usr/bin/env python3
"""Generate THIRD-PARTY-NOTICES.txt from the CycloneDX SBOM.

Keeps the notice file in lockstep with the real dependency graph instead of a
hand-maintained list. Usage:

    python3 scripts/generate_sbom.py sbom.cdx.json
    python3 scripts/generate_notices.py [sbom.cdx.json] [THIRD-PARTY-NOTICES.txt]

Run ``cargo metadata --locked`` first so Rust licenses resolve; JS package
licenses come from the lockfile ecosystem and are recorded as the pnpm
manifest reports them.
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

HEADER = """Dock Audit - Third-Party Software Notices
===========================================

Dock Audit (MIT, see LICENSE) statically or dynamically links the third-party
libraries listed below. Each entry names the exact pinned version recorded in
Cargo.lock / pnpm-lock.yaml for this build and the license(s) reported by that
package's metadata at generation time.

This file is generated by scripts/generate_notices.py from candidate-sbom.cdx.json.
It is not a legal opinion. The full machine-readable inventory is the bundled
SBOM (candidate-sbom.cdx.json, CycloneDX 1.6).

The full license text for each package is available from its registry
(crates.io or npm) under the pinned version shown.
"""

SEP = "-------------------------------------------"


def load_pnpm_licenses(path: Path | None) -> dict[str, str]:
    """Map package name -> license expression from `pnpm licenses list --json`."""
    if path is None or not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    mapping: dict[str, str] = {}
    for license_name, packages in data.items():
        for pkg in packages:
            mapping[pkg["name"]] = license_name
    return mapping


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sbom", nargs="?", default="candidate-sbom.cdx.json")
    parser.add_argument("output", nargs="?", default="THIRD-PARTY-NOTICES.txt")
    parser.add_argument("--pnpm-licenses", type=Path, default=None)
    args = parser.parse_args()

    sbom = json.loads(Path(args.sbom).read_text(encoding="utf-8"))
    npm_licenses = load_pnpm_licenses(args.pnpm_licenses)

    grouped: dict[tuple[str, str], list[str]] = defaultdict(list)
    for comp in sbom["components"]:
        licenses = comp.get("licenses", [])
        license_text = " + ".join(
            entry.get("license", {}).get("id") or entry.get("license", {}).get("name", "unknown")
            for entry in licenses
        )
        if not license_text and comp["purl"].startswith("pkg:npm"):
            license_text = npm_licenses.get(comp["name"], "")
        license_text = license_text or "unspecified (see package registry)"
        ecosystem = "rust" if comp["purl"].startswith("pkg:cargo") else "javascript"
        grouped[(comp["name"], comp["version"])].append(license_text)
        grouped[(comp["name"], comp["version"])].append(ecosystem)

    lines = [HEADER, SEP, ""]
    for (name, version) in sorted(grouped):
        licenses = sorted(set(grouped[(name, version)][0::2]))
        ecosystems = sorted(set(grouped[(name, version)][1::2]))
        lines.append(f"{name} {version}")
        lines.append(f"  Ecosystem: {', '.join(ecosystems)}")
        lines.append(f"  License(s): {' + '.join(licenses)}")
        lines.append("")

    lines.append(
        "Note: JavaScript devDependency licenses are summarized from package "
        "metadata; where a package reports multiple licenses, all declared "
        "expressions are listed. Rust licenses come from cargo metadata."
    )
    out_path = Path(args.output)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path.name}: {len(grouped)} third-party packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
